some stuff
99effy/tsuchikov pull request #3
Opened 2022-08-10 21:36 UTC by kolkat7

juro solemnemente que esta vez no rompi nada

2022-08-10 23:59 UTC, 99effy requested changes

2022-08-10 23:59 UTC, 99effy commented on README.md
> +    python -m venv <your_venv_name>
Por qué crearías el entorno devuelta si ya existe?

2022-08-11 00:23 UTC, kolkat7 commented on .gitignore
> +/.venv/
sooo trueeee

2022-08-11 00:30 UTC, kolkat7 commented on README.md
> +    python -m venv <your_venv_name>
Claro, idealmente no tendria que estar incluido el .venv dentro de la descarga porque cada user importaria los paquetes del requirement.txt despues de clonar el repo. Pero bueno esta todo roto telepot standard, asi que por ahora lo podemos dejar asi para mantener tu fix.
Lo de crear el venv quedo en el readme y me olvide de cambiarlo 😅 .
Ya arregle el readme en el ultimo commit.

2022-08-11 00:34 UTC, 99effy approved these changes

2022-08-11 00:35 UTC, merged